# Generated by Django 4.2 on 2023-05-05 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Central',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=5)),
                ('case', models.CharField(max_length=10)),
                ('option', models.CharField(blank=True, max_length=100, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('timestamp_out', models.DateTimeField(blank=True, null=True)),
                ('timeout', models.BooleanField(default=False)),
                ('post', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='central_admin', to='api.user')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='central_user', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='SelectedEx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseId', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SelectedCent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('central', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange_control.central')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10)),
                ('case_have', models.CharField(blank=True, max_length=10, null=True)),
                ('case_want', models.CharField(blank=True, max_length=10, null=True)),
                ('option', models.CharField(blank=True, max_length=10, null=True)),
                ('task', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('start_date', models.CharField(max_length=10)),
                ('stop_date', models.CharField(max_length=10)),
                ('detail', models.TextField()),
                ('status', models.CharField(max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='DateTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=2)),
                ('value', models.CharField(max_length=2)),
                ('checked', models.BooleanField(default=False)),
                ('am', models.BooleanField(default=False)),
                ('pm', models.BooleanField(default=False)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_time', to='exchange_control.exchange')),
            ],
        ),
        migrations.AddField(
            model_name='central',
            name='selects',
            field=models.ManyToManyField(related_name='cent_selects', through='exchange_control.SelectedCent', to='api.user'),
        ),
    ]
