# Generated by Django 4.2 on 2023-05-05 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
        ('exchange_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedex',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='select_user', to='api.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='selectedex',
            name='caseId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='select_case', to='exchange_control.exchange'),
        ),
    ]
