# Generated by Django 4.2 on 2023-05-05 13:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
        ('exchange_control', '0003_rename_caseid_selectedex_caseex'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedex',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='selectedex',
            name='caseEx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange_control.exchange'),
        ),
        migrations.AlterField(
            model_name='selectedex',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
