# Generated by Django 4.2 on 2023-05-08 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_control', '0004_selectedex_created_at_alter_selectedex_caseex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='case_match',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exchange_control.exchange'),
        ),
    ]
