# Generated by Django 4.2 on 2023-05-05 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='')),
                ('is_read', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_receiver', to='api.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_sender', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='MatchEX',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matchEx', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newMessages', models.IntegerField(blank=True, null=True)),
                ('lastMessage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lastmessage', to='message_control.message')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_user', to='message_control.message')),
            ],
        ),
    ]
