# Generated by Django 4.2 on 2023-05-05 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_control', '0001_initial'),
        ('message_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchex',
            name='case_match',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.CASCADE, related_name='matchCase', to='exchange_control.exchange'),
            preserve_default=False,
        ),
    ]
