# Generated by Django 4.2 on 2023-05-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_control', '0004_selectedex_created_at_alter_selectedex_caseex_and_more'),
        ('api', '0003_notification_author_alter_notification_user'),
        ('message_control', '0002_matchex_case_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='users',
            field=models.ManyToManyField(related_name='chat_user', to='api.user'),
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='message',
        ),
        migrations.RemoveField(
            model_name='matchex',
            name='case_match',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='message',
            field=models.ManyToManyField(related_name='message_user', to='message_control.message'),
        ),
        migrations.AddField(
            model_name='matchex',
            name='case_match',
            field=models.ManyToManyField(related_name='matchCase', to='exchange_control.exchange'),
        ),
    ]
