# Generated by Django 4.2 on 2023-05-07 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_control', '0003_chatroom_users_remove_chatroom_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchex',
            old_name='profile',
            new_name='user',
        ),
    ]
