# Generated by Django 4.2 on 2023-05-07 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_friends'),
        ('message_control', '0005_alter_chatroom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchex',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author_match', to='api.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matchex',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='matchex',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_match', to='api.user'),
        ),
    ]
