# Generated by Django 4.2 on 2023-05-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_control', '0005_exchange_case_match'),
        ('message_control', '0007_alter_chatroom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchex',
            name='case_match',
            field=models.ManyToManyField(blank=True, related_name='matchCase', to='exchange_control.exchange'),
        ),
    ]
