# Generated by Django 4.2 on 2023-05-13 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discord_control', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Channel',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
