# Generated by Django 4.2 on 2023-05-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diag',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('date_update', models.DateField()),
                ('complete', models.IntegerField(blank=True, null=True)),
                ('screen', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('date_update', models.DateField()),
                ('teeth_sum', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Googlesheets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('group', models.CharField(max_length=5)),
                ('subject', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Gs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('no_group', models.CharField(blank=True, max_length=5, null=True)),
                ('no_table', models.CharField(blank=True, max_length=5, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('stID', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Oper',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('date_update', models.DateField()),
                ('class_I', models.IntegerField(blank=True, null=True)),
                ('class_II', models.IntegerField(blank=True, null=True)),
                ('class_III', models.IntegerField(blank=True, null=True)),
                ('class_VI', models.IntegerField(blank=True, null=True)),
                ('class_V', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('date_update', models.DateField()),
                ('treatmentPlan_full', models.IntegerField(blank=True, null=True)),
                ('treatmentPlan_half', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('date_update', models.DateField()),
                ('S', models.IntegerField(blank=True, null=True)),
                ('G', models.IntegerField(blank=True, null=True)),
                ('P', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prosth',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('date_update', models.DateField()),
                ('fixed_PostCore', models.IntegerField(blank=True, null=True)),
                ('fixed_CB', models.IntegerField(blank=True, null=True)),
                ('removable_APD', models.IntegerField(blank=True, null=True)),
                ('removable_RPD', models.IntegerField(blank=True, null=True)),
                ('double_CD', models.IntegerField(blank=True, null=True)),
                ('single_CD', models.IntegerField(blank=True, null=True)),
                ('contrast_CD', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sur',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('date_update', models.DateField()),
                ('tooth_extraction', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
